name: E2e tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - prod
      - test
      - dev*
  pull_request:
    branches:
      - prod

jobs: 
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest

    steps:
      - name: Set environment for branch
        run: |
          echo "${{github.event_name}}"
          echo "${{github.ref}}"
          if [[ ${{ github.event_name }} == push ]]; then
            if [[ ${{ github.ref }} == refs/heads/dev* ]]; then
              echo "SCHEMA_PATH=https://rhubcpapi-dev.connect.test.amazon.auckland.ac.nz/cer-graphql-service/" >> $GITHUB_ENV
              echo "BRANCH_NAME=dev" >> $GITHUB_ENV
            fi
            if [[ ${{ github.ref }} == refs/heads/test ]]; then
              echo "SCHEMA_PATH=https://rhubcpapi.connect.test.amazon.auckland.ac.nz/cer-graphql-service/" >> $GITHUB_ENV
              echo "BRANCH_NAME=test" >> $GITHUB_ENV

            fi
            if [[ ${{ github.ref }} == refs/heads/prod ]]; then
              echo "SCHEMA_PATH=SCHEMA_PATH=https://rhubcpapi.auckland.ac.nz/cer-graphql-service/" >> $GITHUB_ENV
              echo "BRANCH_NAME=prod" >> $GITHUB_ENV
            fi
          else
            echo "SCHEMA_PATH=SCHEMA_PATH=https://rhubcpapi.auckland.ac.nz/cer-graphql-service/" >> $GITHUB_ENV #default to prod for pull_request
            echo "BRANCH_NAME=prod" >> $GITHUB_ENV
          fi
          echo "${{env.BRANCH_NAME}}"
      
      - name: Check out Git repository
        uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14

      # - name: Install Node.js dependencies research-hub-web
      #   working-directory: ./research-hub-web
      #   run: npm ci
      
      # - name: Install GraphQL
      #   working-directory: ./research-hub-web
      #   run: npm install --save graphql

      # - name: Install GraphQL codegen cli
      #   working-directory: ./research-hub-web
      #   run: npm install -g @graphql-codegen/cli

      # - name: Generate GraphQL Schema
      #   working-directory: ./research-hub-web
      #   run: npm run generate
      
      # - name: Install Angular CLI
      #   run: npm install -g @angular/cli

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./research-hub-web
          build: npm run build
          start: npm run start -- -c ${{env.BRANCH_NAME}}
          wait-on: 'http://localhost:4200'